@from="11/2015"
@until="02/2016"
@name="SAP SE"
@location="Walldorf"
@position="Working Student"
@department="Sports Sponsoring Sailing"
@description="Entwicklung einer Bojenpositionsmodellierungs-ansicht mit Java in der SAP Sailing Analytics Suite"