@from="05/2016"
@until="09/2016"
@name="SAP SE"
@location="Walldorf"
@position="Working Student"
@department="PI Technology Process Integration"
@description="Bachelorarbeit über Integrationssysteme auf Field Programmable Gate Arrays (FPGAs)"