@from="07/2014"
@until="09/2014"
@name="SAP SE"
@location="Walldorf"
@position="Working Student"
@department="PI Technology Process Integration"
@description="Konzeption und Integration von Exception Handling in eine Java Integration Domain Specific Language"